-- ============================================================
-- OGBO Web3 App — Supabase Database Schema
-- Based on CLAUDE.md §2 data model
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql/new
--
-- NOTE: This script uses "if not exists" / "drop if exists" patterns
-- so it is safe to re-run on an existing database — it will not
-- destroy existing data, only add missing objects.
-- ============================================================

-- Enable extensions
create extension if not exists "pgcrypto";

-- ============================================================
-- 1. profiles
-- ============================================================
create table if not exists profiles (
  wallet_address text primary key,
  nickname text,
  avatar_url text,
  friend_permission text not null default 'confirm'
    constraint profiles_friend_permission_check
    check (friend_permission in ('anyone', 'confirm', 'reject')),
  updated_at timestamptz not null default now()
);

-- ============================================================
-- 2. contacts
-- ============================================================
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  wallet_a text not null,
  wallet_b text not null,
  status text not null default 'pending'
    constraint contacts_status_check
    check (status in ('pending', 'accepted', 'rejected')),
  request_msg text,
  constraint contacts_wallet_key unique (wallet_a, wallet_b)
);

create index if not exists contacts_status_idx on contacts (status);
create index if not exists contacts_wallet_a_idx on contacts (wallet_a);
create index if not exists contacts_wallet_b_idx on contacts (wallet_b);

-- ============================================================
-- 3. messages
-- ============================================================
create table if not exists messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  chat_id text not null,
  sender text not null,
  content text not null default '',
  msg_type text not null default 'text'
    constraint messages_msg_type_check
    check (msg_type in ('text', 'system', 'image', 'file', 'voice')),
  file_url text,
  file_name text,
  file_size bigint,
  duration integer,
  thumbnail_url text
);

create index if not exists messages_chat_id_idx on messages (chat_id);
create index if not exists messages_chat_created_idx on messages (chat_id, created_at desc);

-- ============================================================
-- 4. groups
-- ============================================================
create table if not exists groups (
  id text primary key,
  created_at timestamptz not null default now(),
  name text not null default '',
  creator text not null,
  members text[] not null default '{}',
  admins text[] not null default '{}',
  announcement text,
  announcement_at timestamptz,
  announcement_by text,
  join_mode text not null default 'approval'
    constraint groups_join_mode_check
    check (join_mode in ('free', 'approval', 'disabled')),
  invite_approval boolean not null default false,
  mute_all boolean not null default false,
  avatar_url text
);

drop index if exists groups_members_idx;
create index if not exists groups_members_idx on groups using gin (members);
create index if not exists groups_creator_idx on groups (creator);

-- ============================================================
-- 5. group_members
-- ============================================================
create table if not exists group_members (
  group_id text not null,
  wallet_address text not null,
  group_nickname text,
  pinned boolean not null default false,
  muted_notifications boolean not null default false,
  joined_at timestamptz not null default now(),
  last_read_announcement_at timestamptz,
  primary key (group_id, wallet_address)
);

create index if not exists group_members_wallet_idx on group_members (wallet_address);

-- ============================================================
-- 6. group_mutes
-- ============================================================
create table if not exists group_mutes (
  id bigint generated by default as identity primary key,
  group_id text not null,
  wallet_address text not null,
  muted_by text not null,
  mute_until timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists group_mutes_group_idx on group_mutes (group_id);
create index if not exists group_mutes_wallet_idx on group_mutes (wallet_address);

-- ============================================================
-- 7. group_invites
-- ============================================================
create table if not exists group_invites (
  id bigint generated by default as identity primary key,
  group_id text not null,
  token uuid not null default gen_random_uuid() unique,
  created_by text not null,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists group_invites_group_idx on group_invites (group_id);
create index if not exists group_invites_token_idx on group_invites (token);

-- ============================================================
-- 8. group_join_requests
-- ============================================================
create table if not exists group_join_requests (
  id bigint generated by default as identity primary key,
  group_id text not null,
  requester text not null,
  invited_by text,
  request_type text not null default 'link'
    constraint group_join_requests_type_check
    check (request_type in ('link', 'invite')),
  status text not null default 'pending'
    constraint group_join_requests_status_check
    check (status in ('pending', 'approved', 'rejected')),
  handled_by text,
  created_at timestamptz not null default now(),
  handled_at timestamptz
);

create index if not exists group_join_requests_group_idx on group_join_requests (group_id);
create index if not exists group_join_requests_status_idx on group_join_requests (group_id, status);

-- ============================================================
-- 9. ota_debug_log
-- ============================================================
create table if not exists ota_debug_log (
  id bigint generated by default as identity primary key,
  device_id text,
  version text,
  platform text,
  message text,
  created_at timestamptz not null default now()
);

create index if not exists ota_debug_log_device_idx on ota_debug_log (device_id);

-- ============================================================
-- Storage Buckets
-- IMPORTANT: Buckets must be created MANUALLY in Supabase Dashboard
-- before running the policies below.
--
-- Steps:
--   1. Go to Supabase Dashboard → Storage → New bucket
--   2. Create these 3 buckets (all public):
--      - chat-files      (for image/file/voice attachments)
--      - avatars         (for user profile avatars)
--      - group-avatars   (for group chat avatars)
--
-- After creating buckets, run the RLS policies below.
-- ============================================================

-- Storage RLS: allow public read + upload for all buckets
drop policy if exists "chat_files_public_read" on storage.objects;
drop policy if exists "chat_files_public_insert" on storage.objects;
create policy "chat_files_public_read" on storage.objects
  for select using (bucket_id = 'chat-files');
create policy "chat_files_public_insert" on storage.objects
  for insert with check (bucket_id = 'chat-files');

drop policy if exists "avatars_public_read" on storage.objects;
drop policy if exists "avatars_public_insert" on storage.objects;
create policy "avatars_public_read" on storage.objects
  for select using (bucket_id = 'avatars');
create policy "avatars_public_insert" on storage.objects
  for insert with check (bucket_id = 'avatars');

drop policy if exists "group_avatars_public_read" on storage.objects;
drop policy if exists "group_avatars_public_insert" on storage.objects;
create policy "group_avatars_public_read" on storage.objects
  for select using (bucket_id = 'group-avatars');
create policy "group_avatars_public_insert" on storage.objects
  for insert with check (bucket_id = 'group-avatars');

-- ============================================================
-- Row Level Security — all fully open
-- (wallet address is verified at app level via wagmi signatures)
-- ============================================================

alter table profiles        enable row level security;
alter table contacts         enable row level security;
alter table messages         enable row level security;
alter table groups           enable row level security;
alter table group_members    enable row level security;
alter table group_mutes      enable row level security;
alter table group_invites    enable row level security;
alter table group_join_requests enable row level security;

drop policy if exists "profiles_select" on profiles;
drop policy if exists "profiles_insert" on profiles;
drop policy if exists "profiles_update" on profiles;
create policy "profiles_select" on profiles for select using (true);
create policy "profiles_insert" on profiles for insert with check (true);
create policy "profiles_update" on profiles for update using (true);

drop policy if exists "contacts_select" on contacts;
drop policy if exists "contacts_insert" on contacts;
drop policy if exists "contacts_update" on contacts;
create policy "contacts_select" on contacts for select using (true);
create policy "contacts_insert" on contacts for insert with check (true);
create policy "contacts_update" on contacts for update using (true);

drop policy if exists "messages_select" on messages;
drop policy if exists "messages_insert" on messages;
create policy "messages_select" on messages for select using (true);
create policy "messages_insert" on messages for insert with check (true);

drop policy if exists "groups_select" on groups;
drop policy if exists "groups_insert" on groups;
drop policy if exists "groups_update" on groups;
create policy "groups_select" on groups for select using (true);
create policy "groups_insert" on groups for insert with check (true);
create policy "groups_update" on groups for update using (true);

drop policy if exists "group_members_select" on group_members;
drop policy if exists "group_members_insert" on group_members;
drop policy if exists "group_members_update" on group_members;
create policy "group_members_select" on group_members for select using (true);
create policy "group_members_insert" on group_members for insert with check (true);
create policy "group_members_update" on group_members for update using (true);

drop policy if exists "group_mutes_select" on group_mutes;
drop policy if exists "group_mutes_insert" on group_mutes;
create policy "group_mutes_select" on group_mutes for select using (true);
create policy "group_mutes_insert" on group_mutes for insert with check (true);

drop policy if exists "group_invites_select" on group_invites;
drop policy if exists "group_invites_insert" on group_invites;
create policy "group_invites_select" on group_invites for select using (true);
create policy "group_invites_insert" on group_invites for insert with check (true);

drop policy if exists "group_join_requests_select" on group_join_requests;
drop policy if exists "group_join_requests_insert" on group_join_requests;
drop policy if exists "group_join_requests_update" on group_join_requests;
create policy "group_join_requests_select" on group_join_requests for select using (true);
create policy "group_join_requests_insert" on group_join_requests for insert with check (true);
create policy "group_join_requests_update" on group_join_requests for update using (true);

-- ============================================================
-- Enable Realtime
-- In Supabase Dashboard > Database > Replication, enable for:
--   contacts, messages, groups, group_members, group_join_requests
--
-- Or run these SQL commands:
-- ============================================================
alter publication supabase_realtime add table contacts;
alter publication supabase_realtime add table messages;
alter publication supabase_realtime add table groups;
alter publication supabase_realtime add table group_members;
alter publication supabase_realtime add table group_join_requests;
